# -*- coding: utf-8 -*-
"""生成器：把 IDA 9.3 全部 action 标签的中文翻译合并进 ida_i18n_zh_CN.json。
键为归一化英文（无 & / ~ 加速键标记）。运行后可删除本文件。"""
import json, os

T = {
# ---- A ----
"About program": "关于程序",
"Add Filter": "添加过滤器",
"Add argument": "添加参数",
"Add breakpoint": "添加断点",
"Add empty line": "添加空行",
"Add encoding": "添加编码",
"Add execution trace": "添加执行跟踪",
"Add node by address": "按地址添加节点",
"Add node by name": "按名称添加节点",
"Add pseudocode comments": "添加伪代码注释",
"Add to vault": "添加到保管库",
"Add xrefs from node": "添加来自节点的交叉引用",
"Add xrefs to node": "添加指向节点的交叉引用",
"Add xrefs to/from node": "添加节点双向交叉引用",
"Add xrefs": "添加交叉引用",
"Add read/write trace": "添加读/写跟踪",
"Add variadic argument": "添加可变参数",
"Add write trace": "添加写跟踪",
"Additional display visible": "附加显示可见",
"Additional binary file": "附加二进制文件",
"Address details": "地址详情",
"Addresses with dereferencing": "带解引用的地址",
"Addresses with names": "带名称的地址",
"Addresses with text": "带文本的地址",
"All error operands": "所有错误操作数",
"All void operands": "所有 void 操作数",
"Analysis indicator": "分析指示器",
"Analyze stack-allocated blocks (current function)": "分析栈分配块(当前函数)",
"Analyze stack-allocated blocks (entire database)": "分析栈分配块(整个数据库)",
"Append function tail": "追加函数尾部",
"Apply all differences in this step (keep local)": "应用本步骤全部差异(保留本地)",
"Apply all differences in this step (pick remote)": "应用本步骤全部差异(采用远端)",
"Apply all differences until this step (pick local)": "应用截至本步骤全部差异(采用本地)",
"Apply all differences until this step (pick remote)": "应用截至本步骤全部差异(采用远端)",
"Apply all non-conflicting differences in this step": "应用本步骤全部无冲突差异",
"Apply selection": "应用选择",
"Array": "数组",
"Assembler directives": "汇编器指示符",
"Auto": "自动",
"Auto resolve (if no conflicts)": "自动解决(如无冲突)",
"Auto resolve, prefer local": "自动解决，优先本地",
"Auto resolve, prefer remote": "自动解决，优先远端",
"Auto-scroll": "自动滚动",
"Apply patches to input file": "将补丁应用到输入文件",
"Back complete": "后退完成",
"Back to previous view": "返回上一视图",
"Bitwise negate": "按位取反",
"Bookmarks": "书签",
"Break on access": "访问时中断",
"C-like format": "类 C 格式",
"Cancel changes": "取消更改",
"Center chunk": "居中显示块",
"Center in window": "在窗口中居中",
"Change calling convention": "更改调用约定",
"Change segment translation": "更改段翻译",
"Change segment register value": "更改段寄存器值",
"Change sign": "更改符号",
"Change stack pointer": "更改栈指针",
"Change tab size": "更改制表符宽度",
"Change the callee address": "更改被调用者地址",
"Change trace description": "更改跟踪描述",
"Change byte": "更改字节",
"Change word": "更改字",
"Char": "字符",
"Character": "字符",
"Check for free update": "检查更新",
"Checkout for copy": "检出以复制",
"Checkout for delete": "检出以删除",
"Checkout for edit": "检出以编辑",
"Checkout for move/rename": "检出以移动/重命名",
"Circle layout": "环形布局",
"Clear Search": "清除搜索",
"Clear overlay": "清除覆盖层",
"Clear trace": "清除跟踪",
"Clear": "清除",
"Clone": "克隆",
"Close window": "关闭窗口",
"Collapse children": "折叠子节点",
"Collapse declarations": "折叠声明",
"Collapse item": "折叠项",
"Collapse parents": "折叠父节点",
"Collapse selected folders": "折叠所选文件夹",
"Columns": "列",
"Commit": "提交",
"Compiler": "编译器",
"Complete": "完成",
"Convert IDB": "转换 IDB",
"Convert to struct *": "转换为结构体指针 *",
"Copy": "复制",
"Copy address to command line": "复制地址到命令行",
"Copy all": "全部复制",
"Copy content": "复制内容",
"Copy field info to pointers": "复制字段信息到指针",
"Copy full type(s)": "复制完整类型",
"Copy line": "复制行",
"Copy location": "复制位置",
"Copy pseudocode to disassembly": "复制伪代码到反汇编",
"Copy size to command line": "复制大小到命令行",
"Copy to CLI": "复制到命令行",
"Copy to assembly": "复制到汇编",
"Copy value": "复制值",
"Create C header file": "创建 C 头文件",
"Create call graph GDL": "创建调用图 GDL",
"Create folder": "创建文件夹",
"Create new struct type": "新建结构体类型",
"Create struct from selection": "从选择创建结构体",
"Create ASM file": "创建 ASM 文件",
"Create C file": "创建 C 文件",
"Create DIF file": "创建 DIF 文件",
"Create EXE file": "创建 EXE 文件",
"Create HTML file": "创建 HTML 文件",
"Create INC file": "创建 INC 文件",
"Create LST file": "创建 LST 文件",
"Create MAP file": "创建 MAP 文件",
"Create SIG file": "创建 SIG 文件",
"Create alignment directive": "创建对齐指示符",
"Create flow chart GDL": "创建流程图 GDL",
"Cross references tree": "交叉引用树",
"Cross references": "交叉引用",
"Cut": "剪切",
"Clear mark": "清除标记",
"Continue backwards": "向后继续",
# ---- D ----
"Database snapshot manager": "数据库快照管理器",
"De-obfuscate arithmetic expressions": "反混淆算术表达式",
"Debugger options": "调试器选项",
"Decompile as call": "反编译为调用",
"Decrease Font Size": "减小字号",
"Decrement value": "值减一",
"Delete": "删除",
"Delete breakpoint": "删除断点",
"Delete function metadata": "删除函数元数据",
"Delete function start": "删除函数起始",
"Delete hidden range": "删除隐藏范围",
"Delete instruction": "删除指令",
"Delete orphan comments": "删除孤立注释",
"Delete pseudocode comments": "删除伪代码注释",
"Delete selected nodes": "删除所选节点",
"Delete variadic argument": "删除可变参数",
"Dereferencing options": "解引用选项",
"Detach from process": "从进程分离",
"Delete type member": "删除类型成员",
"Demangled names": "还原名称",
"Diff against previous revision": "与上一修订对比",
"Diff against the local file": "与本地文件对比",
"Diff against": "与...对比",
"Digraph layout": "有向图布局",
"Disable breakpoint": "禁用断点",
"Disable undo": "禁用撤销",
"Domain API": "域 API",
"Dump history": "转储历史",
"Dump typeinfo to IDC file": "转储类型信息到 IDC 文件",
"Duplicate struct type": "复制结构体类型",
"Dump database to IDC file": "转储数据库到 IDC 文件",
# ---- E ----
"Edit block comment": "编辑块注释",
"Edit breakpoint": "编辑断点",
"Edit comment": "编辑注释",
"Edit exceptions": "编辑异常",
"Edit location": "编辑位置",
"Edit worklist": "编辑工作列表",
"Edit type": "编辑类型",
"Edit": "编辑",
"Edit enum member": "编辑枚举成员",
"Empty navigation stack": "导航栈为空",
"Enable breakpoint": "启用断点",
"Enter anterior lines": "插入前置行",
"Enter comment": "输入注释",
"Enter posterior lines": "插入后置行",
"Enter repeatable comment": "输入可重复注释",
"Enum": "枚举",
"Enum member": "枚举成员",
"Expand children": "展开子节点",
"Expand current node": "展开当前节点",
"Expand node": "展开节点",
"Expand parents": "展开父节点",
"Expand selected folders": "展开所选文件夹",
"Export to file": "导出到文件",
"Export to header file": "导出到头文件",
"Export trace to text file": "导出跟踪到文本文件",
"Exports": "导出表",
"Exit": "退出",
"Export data": "导出数据",
"Extract function": "提取函数",
# ---- F ----
"Feature Flags": "功能标志",
"File history": "文件历史",
"Find functions": "查找函数",
"Find in vault": "在保管库中查找",
"Find path": "查找路径",
"Find register definition": "查找寄存器定义",
"Find register use": "查找寄存器使用",
"Find next": "查找下一个",
"Fit whole program": "适应整个程序",
"Fit window": "适应窗口",
"Focus command line": "聚焦命令行",
"Focus other widget": "聚焦其他窗口",
"Follow in disassembly": "在反汇编中跟随",
"Follow in hex dump": "在十六进制转储中跟随",
"Forbid assignment propagation": "禁止赋值传播",
"Force BL jump": "强制 BL 跳转",
"Full screen": "全屏",
"Function calls": "函数调用",
"Functions": "函数",
"Fuzzy matching": "模糊匹配",
# ---- G-H ----
"Generate HTML": "生成 HTML",
"Generate microcode": "生成微码",
"Generate pseudocode": "生成伪代码",
"Get revision": "获取修订",
"Get the latest revision": "获取最新修订",
"Graph Overview": "图概览",
"Graph view": "图形视图",
"Group nodes": "分组节点",
"Hex View-1": "十六进制视图-1",
"Hex display": "十六进制显示",
"Hex-Rays Decompiler Options": "Hex-Rays 反编译器选项",
"Hide all": "全部隐藏",
"Hide all groups": "隐藏所有分组",
"Hide column": "隐藏列",
"Hide function": "隐藏函数",
"Hide group": "隐藏分组",
"Hide node": "隐藏节点",
"How to buy IDA": "如何购买 IDA",
"IDA View-A": "IDA 视图-A",
"IDA home page": "IDA 主页",
"IDA support forum": "IDA 支持论坛",
"IDS/IDT file": "IDS/IDT 文件",
"Import from file": "从文件导入",
"Imports": "导入表",
"Increase Font Size": "增大字号",
"Increment value": "值加一",
"Insert assertion": "插入断言",
"Insert gap": "插入空隙",
"Insert": "插入",
"Interactive merge": "交互式合并",
"Invert selection": "反选",
"Invert sign": "反转符号",
"Jump by selector": "按选择器跳转",
"Jump by name": "按名称跳转",
"Jump in a new hex window": "在新十六进制窗口中跳转",
"Jump in a new window": "在新窗口中跳转",
"Jump to": "跳转到",
"Jump to IP": "跳转到 IP",
"Jump to a neighboring node (down)": "跳转到相邻节点(下)",
"Jump to a neighboring node (up)": "跳转到相邻节点(上)",
"Jump to address": "跳转到地址",
"Jump to end of line/window bottom/end": "跳转到行尾/窗口底部/末尾",
"Jump to file offset": "跳转到文件偏移",
"Jump to listing end": "跳转到列表末尾",
"Jump to listing start": "跳转到列表开头",
"Jump to matching brace": "跳转到匹配的括号",
"Jump to next fixup": "跳转到下一修正",
"Jump to next function": "跳转到下一个函数",
"Jump to next position": "跳转到下一个位置",
"Jump to prev function": "跳转到上一个函数",
"Jump to pseudocode": "跳转到伪代码",
"Jump to pseudocode in a new view": "在新视图中跳转到伪代码",
"Jump to previous position": "跳转到上一个位置",
"Jump to segment register": "跳转到段寄存器",
"Jump to start of line/window top/start": "跳转到行首/窗口顶部/开头",
"Jump to structure definition": "跳转到结构体定义",
"Jump to the bottom of the window": "跳转到窗口底部",
"Jump to the top of the window": "跳转到窗口顶部",
"Jump to xref globally": "全局跳转到交叉引用",
"Jump to address": "跳转到地址",
"Jump to entry point": "跳转到入口点",
"Jump to function": "跳转到函数",
"Jump to marked position": "跳转到标记位置",
"Jump to problem": "跳转到问题",
"Jump to segment": "跳转到段",
"Jump to xref to operand": "跳转到操作数的交叉引用",
"Jump to xref": "跳转到交叉引用",
"Jump to": "跳转到",
"Keep local change": "保留本地更改",
"Layout calculation": "布局计算",
"Layout graph": "布局图形",
"Legend visible": "图例可见",
"License manager": "许可证管理器",
"List cross references to": "列出到...的交叉引用",
"List cross references from": "列出从...的交叉引用",
"Load DWARF file": "加载 DWARF 文件",
"Load debug symbols": "加载调试符号",
"Load overlay": "加载覆盖层",
"Load trace": "加载跟踪",
"Local Types": "本地类型",
"Local types": "本地类型",
"Lock highlight": "锁定高亮",
"Lower maturity level": "降低成熟度",
"MCP Configuration": "MCP 配置",
"Manage": "管理",
"Manual": "手动",
"Map to another type": "映射到其他类型",
"Map to another variable": "映射到其他变量",
"Map to other widget": "映射到其他窗口",
"Mark as decompiled": "标记为已反编译",
"Mark position": "标记位置",
"Match case": "区分大小写",
"Metadata History": "元数据历史",
"Migrate to another worklist": "迁移到其他工作列表",
"Minimap": "缩略图",
"Modify filters": "修改过滤器",
"Modify value": "修改值",
"Move one character left": "左移一个字符",
"Move one character right": "右移一个字符",
"Move one line down": "下移一行",
"Move one line up": "上移一行",
"Move one page down": "下移一页",
"Move one page up": "上移一页",
"Move one word left": "左移一个单词",
"Move one word right": "右移一个单词",
"Move previous char, in current column": "移到当前列的前一字符",
"Move segment(s)": "移动段",
"Move to beginning of current column": "移到当前列开头",
"Move to beginning of line": "移到行首",
"Move to beginning of text": "移到文本开头",
"Move to end of line": "移到行尾",
"Move to end of text": "移到文本末尾",
"Move to folder": "移动到文件夹",
"Navigation history": "导航历史",
"New": "新建",
"Next Match": "下一个匹配",
"Next chunk": "下一块",
"Next conflict": "下一个冲突",
"Next immediate value": "下一个立即数",
"Next search result": "下一个搜索结果",
"Next sequence of bytes": "下一个字节序列",
"Next text": "下一个文本",
"Next window": "下一个窗口",
"Next code": "下一个代码",
"Next data": "下一个数据",
"Next explored": "下一个已探索",
"Next unexplored": "下一个未探索",
"Next void": "下一个 void",
"Not function": "非函数",
"Notepad": "记事本",
"Objective-C Options": "Objective-C 选项",
"Octal": "八进制",
"Offset (struct)": "偏移(结构体)",
"Offset (current segment)": "偏移(当前段)",
"Offset (data segment)": "偏移(数据段)",
"Offset (user-defined)": "偏移(用户定义)",
"Offset by (any segment)": "偏移(任意段)",
"Online help": "在线帮助",
"Open": "打开",
"Open IDA Feeds": "打开 IDA Feeds",
"Open Search": "打开搜索",
"Open picture": "打开图片",
"Open picture in default viewer": "用默认查看器打开图片",
"Open register window": "打开寄存器窗口",
"Open source file": "打开源文件",
"Open the containing folder": "打开所在文件夹",
"Open this revision": "打开此修订",
"Options": "选项",
"Orthogonal layout": "正交布局",
"Pan the screen down one line": "屏幕下移一行",
"Pan the screen up one line": "屏幕上移一行",
"Parse C header file": "解析 C 头文件",
"Paste": "粘贴",
"Patched bytes": "已打补丁的字节",
"Pick remote change": "采用远端更改",
"Pin node(s)": "固定节点",
"Polar layout": "极坐标布局",
"Previous Match": "上一个匹配",
"Previous chunk": "上一块",
"Previous conflict": "上一个冲突",
"Previous search result": "上一个搜索结果",
"Previous window": "上一个窗口",
"Print graph": "打印图形",
"Print internal flags": "打印内部标志",
"Print register value": "打印寄存器值",
"Print segment registers": "打印段寄存器",
"Proceed to the next step": "进入下一步",
"Proceed to this step": "进入本步骤",
"Process options": "进程选项",
"Processor analysis options": "处理器分析选项",
"Proximity browser": "邻近浏览器",
"Problems": "问题",
"Pull all": "全部拉取",
"Pull function": "拉取函数",
"Pull function start": "拉取函数起始",
"Push all": "全部推送",
"Push function": "推送函数",
"Push function start": "推送函数起始",
"Quick filter": "快速过滤",
"Quick rename": "快速重命名",
"Radial tree layout": "径向树布局",
"Raise maturity level": "提升成熟度",
"Re-analyze global block functions": "重新分析全局块函数",
"Reanalyze program": "重新分析程序",
"Rebuild": "重建",
"Redo": "重做",
"Refresh": "刷新",
"Regular expression": "正则表达式",
"Reload Objective-C info": "重载 Objective-C 信息",
"Reload exceptions": "重载异常",
"Remove Last Filter": "移除最后一个过滤器",
"Remove function argument/retval": "移除函数参数/返回值",
"Remove gap": "移除空隙",
"Remove/Add function retval": "移除/添加函数返回值",
"Rename": "重命名",
"Repeat last palette command": "重复上一个面板命令",
"Report a bug or an issue": "报告缺陷或问题",
"Reset Font Size": "重置字号",
"Reset filters": "重置过滤器",
"Reset graph": "重置图形",
"Reset hidden messages": "重置已隐藏消息",
"Reset natural order": "重置为自然顺序",
"Reset pointer type": "重置指针类型",
"Reset undo history": "重置撤销历史",
"Restore selection": "恢复选择",
"Return license": "归还许可证",
"Revert function start": "还原函数起始",
"Revert if unchanged": "若未更改则还原",
"Revert to defaults": "恢复默认值",
"Revert": "还原",
"Revert CONTAINING_RECORD": "还原 CONTAINING_RECORD",
"Remove function tail": "移除函数尾部",
"Run current": "运行当前",
"Run currently selected script": "运行当前选中的脚本",
"Run to cursor": "运行到光标处",
"Run to cursor (backwards)": "运行到光标处(向后)",
"Run until message received": "运行直到收到消息",
"Run until return": "运行直到返回",
"Rust language helper": "Rust 语言助手",
"Recent scripts": "最近的脚本",
"SVD file management": "SVD 文件管理",
"Sample plugin": "示例插件",
"Save picture": "保存图片",
"Save to file": "保存到文件",
"Save trace": "保存跟踪",
"Save as": "另存为",
"Scan vault": "扫描保管库",
"Script command": "脚本命令",
"Script file": "脚本文件",
"Search Again": "再次搜索",
"Search again": "再次搜索",
"Search direction": "搜索方向",
"Search for pictures": "搜索图片",
"Search highlight down": "搜索高亮向下",
"Search highlight up": "搜索高亮向上",
"Search next": "搜索下一个",
"Search nodes": "搜索节点",
"Search": "搜索",
"Segment registers": "段寄存器",
"Select All": "全选",
"Select all": "全选",
"Select nodes of this color": "选择此颜色的节点",
"Select union field": "选择联合字段",
"Select identifier": "选择标识符",
"Send database": "发送数据库",
"Set IP": "设置 IP",
"Set default segment register value": "设置默认段寄存器值",
"Set node color": "设置节点颜色",
"Set node color to default": "将节点颜色设为默认",
"Set operand type": "设置操作数类型",
"Set password": "设置密码",
"Set tab size": "设置制表符宽度",
"Set type": "设置类型",
"Set call type": "设置调用类型",
"Setup colors": "设置颜色",
"Setup options": "设置选项",
"Setup data types": "设置数据类型",
"Setup": "设置",
"Select union member": "选择联合成员",
"Selectors": "选择子",
"Show": "显示",
"Show all": "全部显示",
"Show all call decompilations": "显示所有调用的反编译",
"Show all xref decompilations": "显示所有交叉引用的反编译",
"Show annotations": "显示注解",
"Show arguments location": "显示参数位置",
"Show command palette": "显示命令面板",
"Show completions": "显示补全",
"Show deleted files": "显示已删除文件",
"Show demangled": "显示还原后的名称",
"Show folders": "显示文件夹",
"Show ignored files": "显示已忽略文件",
"Show other users' worklists": "显示其他用户的工作列表",
"Show overlay info": "显示覆盖层信息",
"Show selection only": "仅显示选中项",
"Show timestamps": "显示时间戳",
"Show trace call graph": "显示跟踪调用图",
"Show trace info": "显示跟踪信息",
"Signatures": "签名",
"Single Float (32-bit)": "单精度浮点 (32 位)",
"Source paths": "源码路径",
"Specify switch idiom": "指定 switch 惯用形式",
"Split expression": "拆分表达式",
"Split memory access": "拆分内存访问",
"Split variable": "拆分变量",
"Stack variable": "栈变量",
"Stack variables": "栈变量",
"Start process": "启动进程",
"Step over": "单步跳过",
"Step over (backwards)": "单步跳过(向后)",
"Step into": "单步步入",
"Step into (backwards)": "单步步入(向后)",
"Stock comments": "常用注释",
"Strings": "字符串",
"Struct var": "结构体变量",
"Structure offset": "结构体偏移",
"Subtract overlay": "减去覆盖层",
"Switch to window #7": "切换到窗口 #7",
"Switch to window #8": "切换到窗口 #8",
"Switch to window #9": "切换到窗口 #9",
"Switch to source": "切换到源码",
"Synchronized": "已同步",
"Select debugger": "选择调试器",
"String literals": "字符串字面量",
"Take database snapshot": "创建数据库快照",
"Take memory snapshot": "创建内存快照",
"Text view": "文本视图",
"Toggle 'Common' panel": "切换“常用”面板",
"Toggle 'Details'": "切换“详情”",
"Toggle SSE intrinsics": "切换 SSE 内建",
"Toggle Sync with cursor": "切换与光标同步",
"Toggle display casts": "切换显示类型转换",
"Toggle hex/dec": "十六进制/十进制切换",
"Toggle renderer": "切换渲染器",
"Toggle value": "切换值",
"Toggle border": "切换边框",
"Tracing options": "跟踪选项",
"Tracing window": "跟踪窗口",
"Tree layout": "树形布局",
"Type libraries": "类型库",
"Uncollapse declarations": "展开声明",
"Uncollapse item": "展开项",
"Undo": "撤销",
"Undo history": "撤销历史",
"Ungroup nodes": "取消节点分组",
"Unhide all groups": "取消隐藏所有分组",
"Unhide group": "取消隐藏分组",
"Unhide all": "全部取消隐藏",
"Unicode pascal (2 byte length)": "Unicode pascal(2 字节长度)",
"Unicode wide pascal (4 byte length)": "Unicode wide pascal(4 字节长度)",
"Unmap variable(s)": "取消映射变量",
"Unmark as decompiled": "取消标记为已反编译",
"Unsort": "取消排序",
"Unsplit expression": "取消拆分表达式",
"Unsplit memory access": "取消拆分内存访问",
"Unsplit variable": "取消拆分变量",
"Use local, discard remote": "使用本地，丢弃远端",
"Use nice names for addresses": "为地址使用友好名称",
"Use predefined color 1": "使用预定义颜色 1",
"Use predefined color 2": "使用预定义颜色 2",
"Use remote, discard local": "使用远端，丢弃本地",
"Use source-level debugging": "使用源码级调试",
"Use this site": "使用此站点",
"View all": "查看全部",
"View function": "查看函数",
"View function start": "查看函数起始",
"View type library contents": "查看类型库内容",
"View worklist": "查看工作列表",
"Whole words": "全字匹配",
"Windows list (next)": "窗口列表(下一个)",
"Windows list": "窗口列表",
"Windows list (prev)": "窗口列表(上一个)",
"Xrefs graph from": "来自...的交叉引用图",
"Xrefs graph to": "到...的交叉引用图",
"Zero value": "值清零",
"Zoom 100%": "缩放 100%",
"Zoom in": "放大",
"Zoom out": "缩小",
"detect and parse golang metadata": "检测并解析 golang 元数据",
"1-byte Integer": "1 字节整数",
"2-byte Integer": "2 字节整数",
"4-byte Integer": "4 字节整数",
"8-byte Integer": "8 字节整数",
"Abort": "中止",
"Add missing fields": "添加缺失字段",
"Add type": "添加类型",
"Add watch": "添加监视",
"Analysis": "分析",
"Analyze module": "分析模块",
"Assemble": "汇编",
"Attach to process": "附加到进程",
"Basic block tracing": "基本块跟踪",
"Begin selection": "开始选择",
"Binary": "二进制",
"Borrow license": "借用许可证",
"Breakpoint list": "断点列表",
"C-style (0 terminated)": "C 风格(以 0 结尾)",
"Calculator": "计算器",
"Close": "关闭",
"Code": "代码",
"Color instruction": "指令着色",
"Colors": "颜色",
"Commits": "提交",
"Connect": "连接",
"Create function": "创建函数",
"Create or edit a function": "创建或编辑函数",
"Create segment": "创建段",
"DBG file": "DBG 文件",
"DOS style ($ terminated)": "DOS 风格(以 $ 结尾)",
"Data": "数据",
"Debugger window": "调试器窗口",
"Decimal": "十进制",
"Delete desktop": "删除桌面",
"Delete function": "删除函数",
"Delete segment": "删除段",
"Delete type": "删除类型",
"Delete watch": "删除监视",
"Delphi (4 byte length)": "Delphi(4 字节长度)",
"Deselect all": "取消全选",
"Details": "详情",
"Disassembly": "反汇编",
"Disconnect": "断开连接",
"Double Float (64-bit)": "双精度浮点 (64 位)",
"Edit function": "编辑函数",
"Edit segment": "编辑段",
"Error operand": "错误操作数",
"Execute": "执行",
"FLIRT signature file": "FLIRT 签名文件",
"Find": "查找",
"Find breakpoint in list": "在列表中查找断点",
"Floating point": "浮点",
"Font": "字体",
"Force BL call": "强制 BL 调用",
"Force call type": "强制调用类型",
"Force zero offset field": "强制零偏移字段",
"Function tracing": "函数跟踪",
"General": "常规",
"Help": "帮助",
"Hex dump": "十六进制转储",
"Hexadecimal": "十六进制",
"Hide": "隐藏",
"Immediate value": "立即数",
"Instruction tracing": "指令跟踪",
"Jump": "跳转",
"Jump to local type": "跳转到本地类型",
"Jump to module base": "跳转到模块基址",
"Jump to operand": "跳转到操作数",
"Load desktop": "加载桌面",
"Local files": "本地文件",
"Locals": "局部变量",
"Long Double (80-bit)": "长双精度 (80 位)",
"Manual instruction": "手动指令",
"Module list": "模块列表",
"Move current segment": "移动当前段",
"Name representation": "名称表示",
"Names": "名称",
"New instance": "新建实例",
"Next CLI": "下一个命令行",
"Number (default)": "数字(默认)",
"Output window": "输出窗口",
"PDB file": "PDB 文件",
"Pascal style (1 byte length)": "Pascal 风格(1 字节长度)",
"Pause process": "暂停进程",
"Previous CLI": "上一个命令行",
"Quick debug view": "快速调试视图",
"Quick run plugins": "快速运行插件",
"Quick start": "快速开始",
"Quick view": "快速视图",
"Rebase program": "重设程序基址",
"Refresh memory": "刷新内存",
"Reload the input file": "重新加载输入文件",
"Rename register": "重命名寄存器",
"Reset decompiler information": "重置反编译器信息",
"Reset desktop": "重置桌面",
"Resume thread": "恢复线程",
"Save": "保存",
"Save desktop": "保存桌面",
"Segment": "段",
"Segments": "段",
"Sequence of bytes": "字节序列",
"Set function end": "设置函数结束",
"Setup hidden items": "设置隐藏项",
"Shortcuts": "快捷键",
"Signed": "有符号",
"Sites": "站点",
"Stack trace": "栈回溯",
"Stack view": "栈视图",
"String": "字符串",
"Suspend thread": "挂起线程",
"TDS file": "TDS 文件",
"Terminate process": "终止进程",
"Text": "文本",
"Thread list": "线程列表",
"Toggle leading zeroes": "切换前导零",
"Toggle skippable instructions": "切换可跳过指令",
"Undefine": "取消定义",
"Unhide": "取消隐藏",
"Unsigned": "无符号",
"Users": "用户",
"Vault files": "保管库文件",
"Watch list": "监视列表",
"Watch view": "监视视图",
"Wide pascal (2 byte length)": "Wide pascal(2 字节长度)",
"Worklists": "工作列表",
"Create folder with items": "创建含内容的文件夹",
"Delete function(s)": "删除函数",
"Expand entire tree": "展开整棵树",
"Collapse entire tree": "折叠整棵树",
"Pseudocode": "伪代码",
}

path = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "ida_i18n_zh_CN.json")
data = json.load(open(path, encoding="utf-8"))
before = len([k for k in data if not k.startswith("_")])
for k, v in T.items():
    if k.startswith("_"):
        continue
    data[k] = v
json.dump(data, open(path, "w", encoding="utf-8"), ensure_ascii=False, indent=2)
after = len([k for k in data if not k.startswith("_")])
print("entries: %d -> %d (added %d)" % (before, after, after - before))
